digraph {
0 [shape=plain label=<<table border="1"><tr><td align="text" border="0" colspan="4">0</td></tr><tr><td port="out0" align="text" colspan="1" cellpadding="1" >0</td><td port="out1" align="text" colspan="1" cellpadding="1" >1</td><td port="out2" align="text" colspan="1" cellpadding="1" >2</td><td port="out3" align="text" colspan="1" cellpadding="1" >3</td></tr></table>>]
0:out2 -> 3:in3 [style=""]
1 [shape=plain label=<<table border="1"><tr><td port="in0" align="text" colspan="2" cellpadding="1" >0</td></tr><tr><td align="text" border="0" colspan="2">1</td></tr><tr><td port="out0" align="text" colspan="1" cellpadding="1" >0</td><td port="out1" align="text" colspan="1" cellpadding="1" >1</td></tr></table>>]
1:out0 -> 3:in2 [style=""]
2 [shape=plain label=<<table border="1"><tr><td port="in0" align="text" colspan="4" cellpadding="1" >0</td><td port="in1" align="text" colspan="4" cellpadding="1" >1</td></tr><tr><td align="text" border="0" colspan="8">2</td></tr><tr><td port="out0" align="text" colspan="2" cellpadding="1" >0</td><td port="out1" align="text" colspan="2" cellpadding="1" >1</td><td port="out2" align="text" colspan="2" cellpadding="1" >2</td><td port="out3" align="text" colspan="2" cellpadding="1" >3</td></tr></table>>]
2:out2 -> 3:in0 [style=""]
3 [shape=plain label=<<table border="1"><tr><td port="in0" align="text" colspan="2" cellpadding="1" >0</td><td port="in1" align="text" colspan="2" cellpadding="1" >1</td><td port="in2" align="text" colspan="2" cellpadding="1" >2</td><td port="in3" align="text" colspan="2" cellpadding="1" >3</td></tr><tr><td align="text" border="0" colspan="8">3</td></tr><tr><td port="out0" align="text" colspan="4" cellpadding="1" >0</td><td port="out1" align="text" colspan="4" cellpadding="1" >1</td></tr></table>>]
3:out0 -> 2:in1 [style=""]
}
