[package]
name = "portmatching"
version = "0.1.0"
edition = "2021"
rust-version = "1.68"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
bitvec = "1.0.1"
portgraph = { git = "https://github.com/cqcl/portgraph", rev = "f35e8e2" }
serde = { version = "1.0.152", features = ["derive"], optional = true}

[features]
serde = ["dep:serde", "portgraph/serde"]

[dev-dependencies]
itertools = "0.10.5"
proptest = "1.1.0"
portgraph = { git = "https://github.com/cqcl/portgraph", rev = "f35e8e2", features = [
    "proptest",
    "serde",
] }
rmp-serde = "1.1.1"
serde = "1.0.156"

[[test]]
name = "from_saved_patterns"
required-features = ["serde"]