[package]
name = "portmatching"
description = "Fast Graph Matching for Port Graphs"
authors = ["Luca Mondada"]
version = "0.1.0"
edition = "2021"
rust-version = "1.69"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
bitvec = "1.0.1"
portgraph = { rev = "3ca1e5f", git = "https://github.com/CQCL/portgraph.git"}
serde = { version = "1.0.152", features = ["derive"], optional = true }

# these are for datagen only
rand = { version = "0.8.5", optional = true }
rmp-serde = { version = "1.1.1", optional = true }
clap = { version = "4.2.2", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "portgraph/serde"]
datagen = ["dep:rand", "dep:rmp-serde", "dep:clap"]

[dev-dependencies]
itertools = "0.10.5"
proptest = "1.1.0"
rmp-serde = "1.1.1"
serde = "1.0.156"
glob = "0.3.1"
criterion = { version = "0.4.0", features = ["html_reports"] }

[dev-dependencies.portgraph]
# version = "0.2.0"
rev = "3ca1e5f"
git = "https://github.com/CQCL/portgraph.git"
features = ["proptest", "serde"]

[[example]]
name = "large_graph"
required-features = ["serde"]

[[test]]
name = "from_saved_patterns"
required-features = ["serde"]

[[bin]]
name = "data_generation"
required-features = ["datagen", "serde"]

[[bench]]
name = "criterion"
harness = false
