on:
  push:
    branches: [bench]
    paths: [datasets/**]

name: "Benchmarking"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repo
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Generate benchmarks
        run: |
          cargo bench

      - name: Push to repo
        run: |
          git add -f target/criterion
          git commit -m "New benchmarking results"
          git push

