on:
  push:
    branches: [main]
    paths-ignore: [src/bin/data_generation.rs]

name: "Benchmarking"

permissions:
  contents: write

concurrency: datasets

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          fetch-depth: 0
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Merge main into bench
        run: |
          git switch bench
          git merge -Xtheirs -m "Merge branch main into bench" origin/main
          git push

      - name: Generate benchmarks
        run: |
          cargo bench

      - name: Push to repo
        run: |
          git add -f target/criterion
          git commit -m "New benchmarking results"
          git push

