on: push

name: CI tests

env:
  CARGO_TERM_COLOR: always
  PROPTEST_CASES: 1024

jobs:
  checks:
    runs-on: ubuntu-latest
    
    name: Formatting and Linting Check

    steps:
      - uses: actions/checkout@v3
        name: Check out repo

      - uses: dtolnay/rust-toolchain@stable
        name: Install toolchain
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Linting (clippy)
        run: cargo clippy --all-targets -- -D warnings

  tests:
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.68.0]
        os:
          - ubuntu-latest
    
    runs-on: ${{ matrix.os }}
    name: Rust ${{ matrix.rust }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        name: Check out repo

      - uses: dtolnay/rust-toolchain@master
        name: Install toolchain
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build package (default features)
        run: cargo build

      - name: Build package (all features)
        run: cargo build --all-features

      - name: Test all features
        run: cargo test --all-features -- --include-ignored