on: push

name: Continuous integration

env:
  CARGO_TERM_COLOR: always
  PROPTEST_CASES: 1024

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.68.0  # MSRV

    steps:
      - uses: actions/checkout@v2
        name: Check out repo

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build package
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: Test all features
        with:
          command: test
          args: --all-features -- --include-ignored

      - uses: actions-rs/cargo@v1
        name: Check formatting
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Lint with Clippy
        with:
          command: clippy
          args: -- -D warnings