on:
  push:
    branches: [bench]
    paths:
      - src/bin/data_generation.rs
      - .github/workflows/datagen.yml

name: "Data Generation for Benchmarking"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Generate datasets
        run: |
          cargo run --bin=data_generation --all-features -- -k1000 -N500 -E1000 -D10 -d10 -n30 -e120
          cargo run --bin=data_generation --all-features -- -K1 -k100 -N500 -E1000 -D10 -o examples/data

      - name: Push to repo
        run: |
          git add -f datasets
          git add -f examples/data
          git commit -m "New datasets"
          git push