on:
  push:
    branches: [main]
    paths: [src/bin/data_generation.rs]

name: "Data Generation for Benchmarking"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          fetch-depth: 0
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Merge main into bench
        run: |
          git switch bench
          git merge -Xtheirs -m "Merge branch main into bench" origin/main
          git push

      - run: |
          cargo run --bin=data_generation --all-features
          git add -f datasets
          git commit -m "New datasets"
          git push