on:
  push:
    branches: [bench]
    paths: 
      - examples/data/**
      - examples/large_graph.rs
      - .github/workflows/profiling.yml
      - src/**
      - "!src/bin/**"

name: "Profiling"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repo
      
      - name: Install flamegraph
        run: |
          sudo apt-get update
          sudo apt install linux-tools-common linux-tools-generic linux-tools-`uname -r`
          cargo install flamegraph
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Run Flamegraphs
        run: |
          cargo flamegraph --example=large_graph --features="serde"

      - name: Push to repo
        run: |
          git add -f flamegraph.svg
          git commit -m "New flamegraph"
          git push
