on:
  push:
    branches: [new-optimise]

name: "Update origin/bench"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Merge new-optimise into bench
        run: |
          git switch bench
          git merge -Xtheirs -m "Merge branch new-optimise into bench" origin/new-optimise
          git push