on:
  push:
    branches: [main]

name: "Update origin/bench"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Merge main into bench
        run: |
          git checkout -b deleteme main
          git reset --soft origin/bench
          git commit -m "Merge main into bench"
          git switch bench
          git cherry-pick deleteme
          git branch -D deleteme
          git push