on:
  push:
    branches: [consume-pattern-opti]

name: "Update origin/bench"

permissions:
  contents: write

jobs:
  all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out repo
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Merge consume-pattern-opti into bench
        run: |
          git switch bench
          git merge -Xtheirs -m "Merge branch consume-pattern-opti into bench" origin/consume-pattern-opti
          git push